# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - feature 

pool:
  name: githubAgent

variables:
  Major: "1"
  Minor: "0"
  Patch: $(Build.BuildId)
  buildVersion: "$(Major).$(Minor).$(Patch)"  
  packageName: "$(Major).$(Minor).$(Patch)-$(Build.SourceBranchName)"
  

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: UseNode@1
  inputs:
    version: '23.x'
    
    
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet Tool'
    
- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: "21"
    jdkArchitectureOption: x64
   # jdkSourceOption: LocalDirectory
    jdkFile: "/home/ortub/jre-8u431-linux-x64.tar.gz"


     

- script: |
    dotnet build --configuration Release
  displayName: 'Build the project'
  
- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_21_X64'    
          

- task: DotNetCoreCLI@2
  condition: eq(variables['Build.SourceBranchName'], 'feature')
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    buildProperties: 'PackageIdPrefix=$(packageName).'  
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'buildVersion' 


- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'MSBuild'
    organization: 'orgitlab'
    projectKey: 'orgitlab_hello'
    projectName: 'hello'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    displayName: 'Restore dependencies'

    
- script: |
    echo "Version: $(buildVersion)"
  displayName: "Print Version to Console"    


- task: DotNetCoreCLI@2
  condition: eq(variables['Build.SourceBranchName'], 'feature')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'b1fdba62-71d1-4e08-8819-7560108d13fb/003c6320-d931-4821-8436-7ef7094cb2fc'
    arguments: '--skip-duplicate'
    
    
-  script: |
    SUBJECT="Azure DevOps Pipeline Status: $(Build.DefinitionName) - $(Build.BuildId)"
    BODY="On $(Build.Repository.Provider) - $(Build.Repository.Name) Repository:"
    BODY="${BODY}The build pipeline has completed with status: $(Agent.JobStatus)\n\n"
    BODY="${BODY}Pipeline Name: $(Build.DefinitionName)\n"
    BODY="${BODY}Branch: $(Build.SourceBranchName)\n"
    BODY="${BODY}Go To Repo: $(Build.Repository.Uri)\n"      
    curl -v --url 'smtp://smtp.gmail.com:587' --ssl-reqd \
        --mail-from "$(GMAIL_USER)" --mail-rcpt "$(GMAIL_USER)" \
        --upload-file <(echo -e "Subject: $SUBJECT\n\n$BODY") \
        --user "$(GMAIL_USER):$(GMAIL_PASSWORD)" --insecure
   displayName: 'Send Pipeline Status Email'
   condition: always()
    
